For Keksobot
htmlacademy-php1/2002509-doingsdone-14 pull request #6
Opened 2022-03-29 07:14 UTC by usershmuser

Отправляю повторный пулл реквест.
Чтобы на сайте академии отобразилось выполненным. Сейчас кексобот не может найти пулл реквест и засчитать задание

2022-03-29 08:42 UTC, olegmifle requested changes
А где изменения? Ничего ж нет (

2022-03-30 03:57 UTC, olegmifle requested changes

2022-03-30 03:57 UTC, olegmifle commented on index.php
> +                        <input class="checkbox__input visually-hidden show_completed" type="checkbox" <?php if ($show_complete_tasks == 1): ?>checked<?php endif; ?>>
Ты можешь использовать тут [тернарный](https://www.php.net/manual/ru/language.operators.comparison.php#language.operators.comparison.ternary) оператор. Кроме того, используй строгое сравнение, вместо нестрогого, что бы избежать неявного приведения типов.

2022-03-30 03:57 UTC, olegmifle commented on index.php
> +                <table class="tasks" <?php if ($show_complete_tasks == 1): ?><tr class="tasks__item task task--completed">
Потерял `>`? в теге table.
Ну и про строгое сравнение не забывай.

2022-03-30 14:53 UTC, usershmuser commented on index.php
> +                <table class="tasks" <?php if ($show_complete_tasks == 1): ?><tr class="tasks__item task task--completed">
Спс)

2022-03-31 06:44 UTC, merged

2022-10-11 09:21 UTC, usershmuser commented
Задание сделал, но оно пока лежит в локалхост директории опенсервера. Как
смогу  запушить изменение, сделаю повторный пулреквест


вт, 29 мар. 2022 г. в 11:43, Oleg Mifle ***@***.***>:

> ***@***.**** requested changes on this pull request.
>
> А где изменения? Ничего ж нет (
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/htmlacademy-php1/2002509-doingsdone-14/pull/6#pullrequestreview-924251055>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYJJXTCYIJOC5W2G5TSFALTVCK7BZANCNFSM5R5N6GKQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>